### ISSUE TITLE
User interface doesn't scale on large 4k displays with 200% scaling

### ISSUE THREAD

**Issue by robertjf** [DashingStrike/Automato#15]
I have a Surface Book with a 3000x2000 display scaled by default to 200% and the Automato interface doesn't scale at all, making it incredibly difficult to read and click on the buttons and other ui elements.

**Comment by Jimbly** [comment]
I believe I have this resolved, and hopefully it has not broken anything, but since it changes some low-level stuff I'd appreciate a test before rolling it out to the general public =).  Try version 2.15 from here: http://dashingstrike.com/Automato/AutomatoInstaller.exe and let me know how it goes!  Right now I just deduce the scaling amount from OS settings, it would be easy to add in a custom scale if anyone wants to tweak the Automato UI scale manually as well.

**Comment by robertjf** [comment]
perfect!  thanks...
I have a possibly related issue where ATITD scripts aren't able to recognise images/text on the interface - will have to investigate some more and will log a bug against the ATITD project if I find a resolution

**Comment by Jimbly** [comment]
Most ATITD scripts require a particular UI scale in ATITD, there's no way around that - Automato is scraping the screen looking for matching images, and if ATITD is scaling them up, it's not going to match.  I think there have been a few scripts made which include multiple images to look for, to get around this, but it's definitely not the norm.

It's possible that if ATITD is running with High-DPI scaling, and Windows is scaling up the window, that would also confuse Automato...

**Comment by robertjf** [comment]
that makes sense; will have a play around and see what I come up with.
